/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AboutRoute } from '../pages/about';
import { Route as _IndexRoute } from '../pages/';
import { Route as _MallangRoute } from '../pages/mallang';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/about': (typeof _AboutRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/mallang': (typeof _MallangRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/about': (typeof _AboutRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/mallang': (typeof _MallangRoute)['_outputType'];
  }
}
